### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by conneralegre** [quicksheep/f1-3-c2p1-colmar-academy#5]
GRADE : EXCEEDS EXPECTATIONS

I really like how this project turned out. I think adding your own styles to this project drove it forward. The usage of alt tags, and having your resources like images and videos stored locally was an excellent idea. On top of all of this, it is fully responsive which really makes it function as a professional site. Something I would change is using more semantic elements like <main> and <section> to section your code out to provide more readability and accessibility to users, or anyone who might be looking over your markup in the future. Overall, excellent!

**Comment by quicksheep** [comment]
Thank you for the thoughtful review!
